name: poseapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4+4
  path_provider: ^2.0.2
  file_picker: ^4.0.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.18.0
  image: ^3.0.1
  image_size_getter: ^2.1.0
  flutter_colorpicker: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/